"""Incremental fleet-health ledger (fleet-config#397).

One markdown file, newest run on top, one entry per machine per run. Two verbs:

  ``previous``  print the most recent run's entries, so the analysis pass can be
                written *against* what was said last time rather than from a
                blank slate. Prints ``NO_PRIOR_ENTRY`` on a first run.
  ``append``    prepend a run's entries below the ledger header.

The ledger lives outside this repo (``~/.claude/fleet-health/``) — it is a
hardware inventory of the user's own machines and is never committed, following
``insights-weekly``'s user-local precedent for persistent per-user output.

Stdlib only. Exit codes: 0 = ok · 2 = bad usage · 5 = ledger unreadable/unwritable.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Optional

HEADER = "# Fleet health ledger\n"
PREAMBLE = (
    "\nHardware health checkups, newest run first. One entry per machine per run;\n"
    "a machine that could not be measured still gets an entry saying why.\n"
    "Generated by `/fleet-health` — never committed, never published publicly.\n"
)

# "## 2026-07-20" — a run heading. Machine entries sit under it as "### <id> — <date>".
RUN_HEADING = re.compile(r"^## (\d{4}-\d{2}-\d{2})\s*$", re.MULTILINE)


def ledger_path(root: Optional[str]) -> Path:
    base = Path(root) if root else Path(
        os.environ.get("FLEET_HEALTH_ROOT", Path.home() / ".claude" / "fleet-health"))
    return base / "fleet-health.md"


def read_ledger(path: Path) -> str:
    if not path.is_file():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        print(f"ledger unreadable: {exc}", file=sys.stderr)
        raise SystemExit(5)


def cmd_previous(args) -> int:
    path = ledger_path(args.root)
    body = read_ledger(path)
    print(f"LEDGER={path}")
    if not body.strip():
        print("NO_PRIOR_ENTRY")
        return 0

    headings = list(RUN_HEADING.finditer(body))
    if not headings:
        print("NO_PRIOR_ENTRY")
        return 0

    first = headings[0]
    end = headings[1].start() if len(headings) > 1 else len(body)
    print(f"PREVIOUS_RUN={first.group(1)}")
    print()
    print(body[first.start():end].rstrip())
    return 0


def cmd_append(args) -> int:
    path = ledger_path(args.root)

    entries = ""
    if args.file:
        source = Path(args.file)
        if not source.is_file():
            print(f"entries file not found: {source}", file=sys.stderr)
            return 2
        entries = source.read_text(encoding="utf-8", errors="replace").strip()
    else:
        entries = sys.stdin.read().strip()

    if not entries:
        print("refusing to append an empty run entry", file=sys.stderr)
        return 2

    existing = read_ledger(path)
    if existing.strip():
        # Drop the header/preamble; we re-emit them above the new run.
        headings = list(RUN_HEADING.finditer(existing))
        tail = existing[headings[0].start():].rstrip() if headings else ""
    else:
        tail = ""

    block = f"## {args.date}\n\n{entries}\n"
    parts = [HEADER, PREAMBLE, "\n", block]
    if tail:
        parts += ["\n", tail, "\n"]

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("".join(parts), encoding="utf-8")
    except OSError as exc:
        print(f"ledger unwritable: {exc}", file=sys.stderr)
        return 5

    print(f"LEDGER={path}")
    print(f"APPENDED={args.date}")
    return 0


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Fleet-health incremental ledger")
    parser.add_argument("--root", default=None,
                        help="ledger root (default ~/.claude/fleet-health)")
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("previous", help="print the most recent run's entries")

    append = sub.add_parser("append", help="prepend a run's entries")
    append.add_argument("--date", required=True, help="run date (YYYY-MM-DD)")
    append.add_argument("--file", default=None,
                        help="markdown file of this run's entries (default: stdin)")

    args = parser.parse_args(argv)
    if args.cmd == "previous":
        return cmd_previous(args)
    return cmd_append(args)


if __name__ == "__main__":
    sys.exit(main())
