"""Aggregate per-repo ``.fleet.toml`` declarations into the system-map data.

``architecture/fleet.data.js`` is the file the renderer (``system-map.html``) and
the drift test (``tests/run_acceptance.py``) read. It is now *generated* from two
inputs:

* ``architecture/fleet.residual.json`` — hand-maintained. Holds the non-repo
  structure (access / edge / compute / external / principles), every repo's card
  as an ordered *fallback*, and an ``_adopted`` registry naming the repos that
  MUST self-describe via a root ``.fleet.toml``.
* each fleet repo's root ``.fleet.toml`` — authoritative for that repo's card
  when present (overrides the residual fallback in place, so curated order holds).

Why a registry instead of deleting fallback cards on adoption: keeping the card
in place preserves the curated map order, and ``_adopted`` is what makes a
*deleted* ``.fleet.toml`` fail loud — the drift test asserts every adopted repo
still carries one, so per-repo metadata can never silently go stale.

Usage::

    py skills/system-map/build_data.py            # regenerate fleet.data.js
    py skills/system-map/build_data.py --check     # exit 1 if the file is stale

``.fleet.toml`` schema (full reference: architecture/README.md)::

    layer       = "working-pipe"   # governance | enabling | working-web | working-pipe
    icon        = "📄"
    description = "PDF → clean Markdown for LLMs."   # injected as innerHTML
    # optional:
    display_name = "grocery"        # when the card label ≠ repo dir name
    port         = ":8444"
    chips        = ["whisper :8090"]
    tag          = ["→", "Notion"]  # [relation, target]
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_JS = REPO_ROOT / "architecture" / "fleet.data.js"
RESIDUAL = REPO_ROOT / "architecture" / "fleet.residual.json"
PROJECTS_TOML = REPO_ROOT / "hooks" / "projects.toml"

# .fleet.toml `layer` → the fleet.data.js section it lands in.
LAYER_SECTION = {
    "governance": "governance",
    "enabling": "enabling",
    "working-web": "web",
    "working-pipe": "pipe",
}

HEADER = """\
// fleet.data.js — the data behind the system map. GENERATED by
// skills/system-map/build_data.py — DO NOT hand-edit. Edit each repo's root
// `.fleet.toml` (authoritative) or `architecture/fleet.residual.json` (the
// non-repo structure + fallback cards), then regenerate:
//   py skills/system-map/build_data.py
// Loaded as plain JS (works under file://, no CORS): sets window.FLEET.
// The body is strict JSON so Python (build_data.py, the /system-map skill, and
// the drift test in tests/run_acceptance.py) can read it too: strip
// "window.FLEET =" + trailing ";".
//   - compute specs are PLACEHOLDERS; real values live in system-map.local.js.
//   - "repo" is set only when the display name differs from the repo name.
// Membership is governed by hooks/projects.toml (minus [global] architecture_ignore).
"""

# Canonical key order inside a repo card, matching the committed style.
_CARD_KEY_ORDER = ["ic", "nm", "repo", "port", "ds", "chips", "tag"]


def load_residual(path: Path = RESIDUAL) -> dict:
    """Parse the hand-maintained residual (strict JSON, includes ``_adopted``)."""
    return json.loads(path.read_text(encoding="utf-8"))


def fleet_repos(projects_toml: Path = PROJECTS_TOML) -> dict[str, Path]:
    """Return ``{repo_name: repo_dir}`` for the architecture fleet.

    Fleet = every ``[<name>]`` table carrying a ``cwd_prefix`` − the
    ``[global] architecture_ignore`` list (vendored / legacy / out-of-scope).
    """
    toml = tomllib.loads(projects_toml.read_text(encoding="utf-8"))
    ignore = set(toml.get("global", {}).get("architecture_ignore", []))
    return {
        name: Path(tbl["cwd_prefix"])
        for name, tbl in toml.items()
        if name != "global" and isinstance(tbl, dict) and "cwd_prefix" in tbl
        and name not in ignore
    }


def card_from_toml(repo_name: str, meta: dict) -> tuple[str, dict]:
    """Build ``(section, card)`` from a parsed ``.fleet.toml``.

    Raises ``ValueError`` on a missing/invalid ``layer`` or missing required field
    so a malformed declaration fails loud rather than silently dropping a repo.
    """
    layer = meta.get("layer")
    if layer not in LAYER_SECTION:
        raise ValueError(
            f"{repo_name}: .fleet.toml `layer` must be one of {sorted(LAYER_SECTION)}, got {layer!r}"
        )
    for required in ("icon", "description"):
        if not meta.get(required):
            raise ValueError(f"{repo_name}: .fleet.toml is missing required `{required}`")

    nm = meta.get("display_name") or repo_name
    card: dict = {"ic": meta["icon"], "nm": nm}
    if nm != repo_name:  # keep the repo handle when the display label differs
        card["repo"] = repo_name
    if "port" in meta:
        card["port"] = meta["port"]
    card["ds"] = meta["description"]
    if "chips" in meta:
        card["chips"] = list(meta["chips"])
    if "tag" in meta:
        card["tag"] = list(meta["tag"])
    return LAYER_SECTION[layer], {k: card[k] for k in _CARD_KEY_ORDER if k in card}


def _card_repo(entry: dict) -> str:
    """The repo name an existing card represents (``repo`` overrides display ``nm``)."""
    return entry.get("repo", entry["nm"])


def build(residual: dict, repos: dict[str, Path]) -> dict:
    """Overlay every repo's ``.fleet.toml`` card onto the residual fallback.

    Adopted repos override their fallback card *in place* (curated order holds);
    a repo new to the map appends to its section. ``_adopted`` is dropped — it is
    residual metadata, not map data.
    """
    data = copy.deepcopy(residual)
    data.pop("_adopted", None)
    for repo_name, repo_dir in sorted(repos.items()):
        toml_path = repo_dir / ".fleet.toml"
        if not toml_path.is_file():
            continue  # fallback: keep whatever the residual already has
        meta = tomllib.loads(toml_path.read_text(encoding="utf-8"))
        section, card = card_from_toml(repo_name, meta)
        bucket = data.setdefault(section, [])
        for i, entry in enumerate(bucket):
            if _card_repo(entry) == repo_name:
                bucket[i] = card
                break
        else:
            bucket.append(card)
    return data


def _dump(obj) -> str:
    """One-line JSON in the committed style (``{"k": "v", ...}``)."""
    return json.dumps(obj, ensure_ascii=False, separators=(", ", ": "))


def serialize(data: dict) -> str:
    """Render the dict back to the committed ``fleet.data.js`` text."""
    parts = []
    for key, val in data.items():
        if isinstance(val, list):
            body = ",\n".join(f"    {_dump(e)}" for e in val)
            parts.append(f'  "{key}": [\n{body}\n  ]')
        else:  # compute dict — inline
            parts.append(f'  "{key}": {_dump(val)}')
    return HEADER + "window.FLEET = {\n" + ",\n".join(parts) + "\n};\n"


def regenerate() -> str:
    """Build the aggregated fleet data and return the serialized ``fleet.data.js``."""
    return serialize(build(load_residual(), fleet_repos()))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Aggregate per-repo .fleet.toml into fleet.data.js.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if fleet.data.js is stale (do not write)")
    args = ap.parse_args(argv)

    try:
        rendered = regenerate()
    except ValueError as exc:
        print(f"build_data: {exc}", file=sys.stderr)
        return 1

    current = DATA_JS.read_text(encoding="utf-8")
    if args.check:
        if rendered != current:
            print("build_data: fleet.data.js is STALE — run "
                  "`py skills/system-map/build_data.py` and commit.", file=sys.stderr)
            return 1
        print("build_data: fleet.data.js is up to date.")
        return 0

    if rendered != current:
        DATA_JS.write_text(rendered, encoding="utf-8")
        print(f"build_data: regenerated {DATA_JS.name}.")
    else:
        print(f"build_data: {DATA_JS.name} already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
