"""Aggregate per-repo ``.fleet.toml`` declarations into the system-map data.

``architecture/fleet.data.js`` is the file the renderer (``system-map.html``) and
the drift test (``tests/run_acceptance.py``) read. It is now *generated* from two
inputs:

* ``architecture/fleet.residual.json`` — hand-maintained. Holds the non-repo
  structure (access / edge / compute / external / principles), every repo's card
  as an ordered *fallback*, and an ``_adopted`` registry naming the repos that
  MUST self-describe via a root ``.fleet.toml``.
* each fleet repo's root ``.fleet.toml`` — authoritative for that repo's card
  when present (overrides the residual fallback in place, so curated order holds).
  Read from the repo's **committed default branch** (``git show <origin/HEAD>``),
  not the working tree — so the map and the drift gate are independent of whatever
  branch each repo happens to be checked out on.

Why a registry instead of deleting fallback cards on adoption: keeping the card
in place preserves the curated map order, and ``_adopted`` is what makes a
*deleted* ``.fleet.toml`` fail loud — the drift test asserts every adopted repo
still carries one, so per-repo metadata can never silently go stale.

Usage (invoke the resolved Python path directly — a bare ``py``/``python`` is
not reliably on ``PATH`` on this machine; see ``_lib.find_python_executable``)::

    E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/build_data.py            # regenerate fleet.data.js
    E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/build_data.py --check     # exit 1 if the file is stale

Either form also exits 1 when it refused an over-cap description (named on
stderr); the regenerated file then carries that repo's residual fallback card.

``.fleet.toml`` schema (full reference: architecture/README.md)::

    layer       = "working-pipe"   # governance | enabling | working-web | working-pipe
    icon        = "📄"
    description = "PDF → clean Markdown for LLMs."   # injected as innerHTML; ≤ DESCRIPTION_CAP[layer]
    # optional:
    display_name = "grocery"        # when the card label ≠ repo dir name
    port         = ":8444"
    chips        = ["whisper :8090"]
    tag          = ["→", "Notion"]  # [relation, target]
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "skills" / "_lib"))
import fleet_repo_scan  # noqa: E402
import git_run  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]
DATA_JS = REPO_ROOT / "architecture" / "fleet.data.js"
RESIDUAL = REPO_ROOT / "architecture" / "fleet.residual.json"
PROJECTS_TOML = REPO_ROOT / "hooks" / "projects.toml"

# .fleet.toml `layer` → the fleet.data.js section it lands in.
LAYER_SECTION = {
    "governance": "governance",
    "enabling": "enabling",
    "working-web": "web",
    "working-pipe": "pipe",
}

HEADER = """\
// fleet.data.js — the data behind the system map. GENERATED by
// .claude/skills/system-map/build_data.py — DO NOT hand-edit. Edit each repo's root
// `.fleet.toml` (authoritative) or `architecture/fleet.residual.json` (the
// non-repo structure + fallback cards), then regenerate:
//   E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/build_data.py
// Loaded as plain JS (works under file://, no CORS): sets window.FLEET.
// The body is strict JSON so Python (build_data.py, the /system-map skill, and
// the drift test in tests/run_acceptance.py) can read it too: strip
// "window.FLEET =" + trailing ";".
//   - compute specs are PLACEHOLDERS; real values live in system-map.local.js.
//   - "repo" is set only when the display name differs from the repo name.
// Membership is governed by hooks/projects.toml (minus [global] architecture_ignore).
"""

# Longest `description` (characters, as written) each layer's card shows in two
# lines. Measured in headless Chrome on system-map.html: the widest prose that
# still wraps to two lines was 72 (pipe card, 181 px at 10.5 px), 98 (web,
# 234 px at 10.5 px), 84 (enabling, 232 px at 12 px) and 137 (governance,
# 513 px at the page font); each cap rounds down to keep a margin. Counting the
# text as written (`&amp;` is five) only errs short. Detail beyond that goes in
# `chips`/`tag` (fleet-config#1250).
DESCRIPTION_CAP = {
    "governance": 130,
    "enabling": 80,
    "working-web": 95,
    "working-pipe": 70,
}


class DescriptionTooLong(ValueError):
    """A `.fleet.toml` description longer than its layer's card holds."""


# Canonical key order inside a repo card, matching the committed style.
_CARD_KEY_ORDER = ["ic", "nm", "repo", "port", "ds", "chips", "tag"]


def load_residual(path: Path = RESIDUAL) -> dict:
    """Parse the hand-maintained residual (strict JSON, includes ``_adopted``)."""
    return json.loads(path.read_text(encoding="utf-8"))


def fleet_repos(projects_toml: Path = PROJECTS_TOML) -> dict[str, Path]:
    """Return ``{repo_name: repo_dir}`` for the architecture fleet.

    Fleet = every ``[<name>]`` table carrying a ``cwd_prefix`` − the
    ``[global] architecture_ignore`` list (vendored / legacy / out-of-scope).
    """
    return fleet_repo_scan.fleet_repos(projects_toml)


def _default_ref(repo_dir: Path) -> str | None:
    """The ref to read a repo's committed ``.fleet.toml`` from (its default branch).

    Resolves ``origin/HEAD`` (e.g. ``origin/main``); falls back through common
    default-branch names. Uses remote-tracking refs so the result is independent
    of which branch the repo is checked out on, and needs no network.
    """
    return fleet_repo_scan.default_ref(repo_dir)


def read_fleet_toml(repo_dir: Path) -> str | None:
    """Return the ``.fleet.toml`` text committed on ``repo_dir``'s default branch.

    Reads ``git show <default-ref>:.fleet.toml`` (not the working tree) so a repo
    parked on a feature branch that predates the file still reports its real card.
    Returns ``None`` when the repo has no default ref or no committed ``.fleet.toml``.
    """
    ref = _default_ref(repo_dir)
    if ref is None:
        return None
    shown = git_run.run_git_bytes(["-C", str(repo_dir), "show", f"{ref}:.fleet.toml"])
    return shown.stdout.decode("utf-8") if shown.returncode == 0 else None


def card_from_toml(repo_name: str, meta: dict) -> tuple[str, dict]:
    """Build ``(section, card)`` from a parsed ``.fleet.toml``.

    Raises ``ValueError`` on a missing/invalid ``layer`` or missing required field
    so a malformed declaration fails loud rather than silently dropping a repo,
    and ``DescriptionTooLong`` when ``description`` exceeds ``DESCRIPTION_CAP``.
    """
    layer = meta.get("layer")
    if layer not in LAYER_SECTION:
        raise ValueError(
            f"{repo_name}: .fleet.toml `layer` must be one of {sorted(LAYER_SECTION)}, got {layer!r}"
        )
    for required in ("icon", "description"):
        if not meta.get(required):
            raise ValueError(f"{repo_name}: .fleet.toml is missing required `{required}`")
    cap = DESCRIPTION_CAP[layer]
    if len(meta["description"]) > cap:
        raise DescriptionTooLong(
            f"{repo_name}: .fleet.toml `description` is {len(meta['description'])} chars; "
            f"a {layer} card holds {cap} (two lines). Shorten it in {repo_name}; "
            "put extra detail in `chips`/`tag`."
        )

    nm =meta.get("display_name") or repo_name
    card: dict = {"ic": meta["icon"], "nm": nm}
    if nm != repo_name:  # keep the repo handle when the display label differs
        card["repo"] = repo_name
    if "port" in meta:
        card["port"] = meta["port"]
    card["ds"] = meta["description"]
    if "chips" in meta:
        card["chips"] = list(meta["chips"])
    if "tag" in meta:
        card["tag"] = list(meta["tag"])
    return LAYER_SECTION[layer], {k: card[k] for k in _CARD_KEY_ORDER if k in card}


def _card_repo(entry: dict) -> str:
    """The repo name an existing card represents (``repo`` overrides display ``nm``)."""
    return entry.get("repo", entry["nm"])


def build(residual: dict, repos: dict[str, Path], refused: list[str] | None = None) -> dict:
    """Overlay every repo's ``.fleet.toml`` card onto the residual fallback.

    Adopted repos override their fallback card *in place* (curated order holds);
    a repo new to the map appends to its section. ``_adopted`` is dropped — it is
    residual metadata, not map data.

    An over-cap description is refused: the repo keeps its residual fallback
    card and the reason is appended to ``refused``. With no fallback card the
    refusal raises, since the repo would otherwise vanish from the map.
    """
    data = copy.deepcopy(residual)
    data.pop("_adopted", None)
    fallback = {_card_repo(e) for s in LAYER_SECTION.values() for e in data.get(s, [])}
    for repo_name, repo_dir in sorted(repos.items()):
        text = read_fleet_toml(repo_dir)
        if text is None:
            continue  # fallback: keep whatever the residual already has
        try:
            section, card = card_from_toml(repo_name, tomllib.loads(text))
        except DescriptionTooLong as exc:
            if repo_name not in fallback:
                raise DescriptionTooLong(f"{exc} No residual fallback card to show instead.") from exc
            if refused is not None:
                refused.append(str(exc))
            continue
        bucket = data.setdefault(section, [])
        for i, entry in enumerate(bucket):
            if _card_repo(entry) == repo_name:
                bucket[i] = card
                break
        else:
            bucket.append(card)
    return data


def _dump(obj) -> str:
    """One-line JSON in the committed style (``{"k": "v", ...}``)."""
    return json.dumps(obj, ensure_ascii=False, separators=(", ", ": "))


def serialize(data: dict) -> str:
    """Render the dict back to the committed ``fleet.data.js`` text."""
    parts = []
    for key, val in data.items():
        if isinstance(val, list):
            body = ",\n".join(f"    {_dump(e)}" for e in val)
            parts.append(f'  "{key}": [\n{body}\n  ]')
        else:  # compute dict — inline
            parts.append(f'  "{key}": {_dump(val)}')
    return HEADER + "window.FLEET = {\n" + ",\n".join(parts) + "\n};\n"


def regenerate(refused: list[str] | None = None) -> str:
    """Build the aggregated fleet data and return the serialized ``fleet.data.js``.

    Over-cap descriptions are reported through ``refused`` (see ``build``).
    """
    return serialize(build(load_residual(), fleet_repos(), refused))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Aggregate per-repo .fleet.toml into fleet.data.js.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if fleet.data.js is stale (do not write)")
    args = ap.parse_args(argv)

    refused: list[str] = []
    try:
        rendered = regenerate(refused)
    except ValueError as exc:
        print(f"build_data: {exc}", file=sys.stderr)
        return 1
    for reason in refused:
        print(f"build_data: REFUSED {reason} Kept its residual fallback card.", file=sys.stderr)

    current = DATA_JS.read_text(encoding="utf-8")
    if args.check:
        if rendered != current:
            print("build_data: fleet.data.js is STALE — run "
                  "`E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/build_data.py` and commit.", file=sys.stderr)
            return 1
        print("build_data: fleet.data.js is up to date.")
        return 1 if refused else 0

    if rendered != current:
        DATA_JS.write_text(rendered, encoding="utf-8")
        print(f"build_data: regenerated {DATA_JS.name}.")
    else:
        print(f"build_data: {DATA_JS.name} already up to date.")
    return 1 if refused else 0


if __name__ == "__main__":
    sys.exit(main())
