"""Render ``architecture/fleet.data.js`` as a Mermaid flowchart — text-native.

The PNG (`render.py`) is the human/chat artifact; this is the **agent** artifact —
a compact, always-current picture of the fleet an LLM can read as text without a
browser or an image decoder. Same single source of truth (`fleet.data.js`), a
second consumer, no new crawl logic.

Deterministic by construction, same discipline as ``build_data.py``:
* layer order is fixed (``governance``, ``enabling``, ``web``, ``pipe``);
* repos within a layer keep the array order already curated in ``fleet.data.js``;
* node ids are a plain slug of the repo's identity (``repo`` field if set, else
  ``nm`` — the same key `whatchanged.py`/`run_acceptance.py` already use), never
  derived from anything that varies run-to-run.

Kept deliberately lean for the ``global-CLAUDE.md`` embed (every-session context
cost): nodes carry **icon + name only**, never the ``ds`` description prose (the
priciest field, and already redundant with what an agent reads once it's actually
inside a given repo). ``access``/``edge``/``compute``/``external``/``principles``
are skipped entirely — narrative already covered in ``ARCHITECTURE.md``, not
repo-relationship data. Edges come only from each card's explicit ``tag`` field
(``["uses", "hub"]`` etc.) — never inferred/guessed. A tag's target text doesn't
always name another mapped repo (``"hub + whisper"``, ``"Stripe"``, …), so it gets
its own small lightweight node rather than a fuzzy match onto an existing one —
literal reflection of the curated data, not invented structure.

Usage (invoke the resolved Python path directly — see ``build_data.py``)::

    E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/render_mermaid.py                    # regenerate system-map.mmd (+ global-CLAUDE.md block)
    E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/render_mermaid.py --check             # exit 1 if system-map.mmd is stale
    E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/render_mermaid.py --no-update-claude-md  # .mmd only, skip the CLAUDE.md block
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DATA_JS = REPO_ROOT / "architecture" / "fleet.data.js"
MMD_OUT = REPO_ROOT / "architecture" / "system-map.mmd"
GLOBAL_CLAUDE_MD = REPO_ROOT / "global-CLAUDE.md"

# The sections of fleet.data.js whose cards are real fleet repos, in the fixed
# render order (matches the drift guard in tests/run_acceptance.py).
SECTIONS = ["governance", "enabling", "web", "pipe"]
SECTION_TITLES = {
    "governance": "Governance",
    "enabling": "Enabling",
    "web": "Web",
    "pipe": "Pipelines",
}

HEADER = """\
%% architecture/system-map.mmd — Mermaid rendering of architecture/fleet.data.js.
%% GENERATED by .claude/skills/system-map/render_mermaid.py — DO NOT hand-edit.
%% Regenerate: E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/render_mermaid.py
"""

CLAUDE_MD_START = "<!-- system-map:mermaid:start -->"
CLAUDE_MD_END = "<!-- system-map:mermaid:end -->"

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slug(text: str) -> str:
    """A stable Mermaid-safe node id: lowercase, non-alnum runs collapsed to ``_``."""
    return _SLUG_RE.sub("_", text.lower()).strip("_")


def _escape(text: str) -> str:
    """Escape the one character that would break a quoted Mermaid node label."""
    return text.replace('"', "&quot;")


def load_data(js_text: str) -> dict:
    """Slice the strict-JSON object out of ``window.FLEET = { … };`` (same trick
    every other consumer of this file uses — see ``run_acceptance.py``)."""
    return json.loads(js_text[js_text.index("{"): js_text.rindex("}") + 1])


def _node_id(card: dict) -> str:
    return slug(card.get("repo", card["nm"]))


def render_flowchart(data: dict) -> str:
    """Build the flowchart body (no header comment) — pure function of ``data``."""
    lines = ["flowchart LR"]

    for section in SECTIONS:
        lines.append(f'  subgraph {section}["{SECTION_TITLES[section]}"]')
        for card in data.get(section, []):
            label = _escape(f'{card["ic"]} {card["nm"]}')
            lines.append(f'    {_node_id(card)}["{label}"]')
        lines.append("  end")

    # Edges from each card's `tag` field, in the same fixed iteration order.
    # A tag's target text gets its own lightweight node the first time it's
    # seen (dict preserves insertion order) rather than being fuzzy-matched
    # onto an existing repo node.
    target_ids: dict[str, str] = {}
    edges: list[tuple[str, str, str]] = []
    for section in SECTIONS:
        for card in data.get(section, []):
            tag = card.get("tag")
            if not tag:
                continue
            relation, target_text = tag[0], tag[1]
            target_id = target_ids.setdefault(target_text, "t_" + slug(target_text))
            edges.append((_node_id(card), relation, target_id))

    if target_ids:
        lines.append('  subgraph targets["Referenced"]')
        for text, tid in target_ids.items():
            lines.append(f'    {tid}["{_escape(text)}"]')
        lines.append("  end")

    for node_id, relation, target_id in edges:
        lines.append(f"  {node_id} -->|{relation}| {target_id}")

    return "\n".join(lines) + "\n"


def render(data: dict) -> str:
    """The full committed ``system-map.mmd`` text: header comment + flowchart."""
    return HEADER + render_flowchart(data)


def regenerate(data_path: Path = DATA_JS) -> str:
    return render(load_data(data_path.read_text(encoding="utf-8")))


def update_claude_md(flowchart_body: str, path: Path = GLOBAL_CLAUDE_MD) -> bool:
    """Replace the marked block in ``global-CLAUDE.md`` with the fenced diagram.

    Inserts a new ``### Fleet map`` subsection (with markers) right after "Every
    repo carries a `.fleet.toml`" the first time this runs; every run after just
    replaces the content between the existing markers. Returns whether the file
    changed (write is skipped when it didn't, so an unchanged week makes no diff).
    """
    text = path.read_text(encoding="utf-8")
    block = (
        f"{CLAUDE_MD_START}\n"
        "### Fleet map\n\n"
        "Text-native picture of the fleet's repos and how they relate — regenerated by `/system-map` "
        "from the same `fleet.data.js` the PNG map reads; icons + names only, no descriptions (kept lean "
        "for every-session context cost). Edges come from each repo's `.fleet.toml` `tag` field.\n\n"
        "```mermaid\n"
        f"{flowchart_body}"
        "```\n"
        f"{CLAUDE_MD_END}"
    )

    if CLAUDE_MD_START in text and CLAUDE_MD_END in text:
        start = text.index(CLAUDE_MD_START)
        end = text.index(CLAUDE_MD_END) + len(CLAUDE_MD_END)
        new_text = text[:start] + block + text[end:]
    else:
        anchor = "\n## Local infrastructure\n"
        if anchor not in text:
            raise RuntimeError("update_claude_md: couldn't find the '## Local infrastructure' anchor")
        new_text = text.replace(anchor, f"\n{block}\n{anchor}", 1)

    if new_text == text:
        return False
    path.write_text(new_text, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render fleet.data.js as a Mermaid flowchart.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if system-map.mmd (or the global-CLAUDE.md block) is stale")
    ap.add_argument("--no-update-claude-md", action="store_true",
                    help="skip refreshing the marked block in global-CLAUDE.md")
    args = ap.parse_args(argv)

    data = load_data(DATA_JS.read_text(encoding="utf-8"))
    rendered = render(data)
    flowchart_body = render_flowchart(data)

    current = MMD_OUT.read_text(encoding="utf-8") if MMD_OUT.exists() else None
    mmd_fresh = rendered == current

    claude_md_fresh = True
    if not args.no_update_claude_md:
        claude_md_text = GLOBAL_CLAUDE_MD.read_text(encoding="utf-8")
        expected_block_start = f"{CLAUDE_MD_START}\n### Fleet map"
        claude_md_fresh = (
            CLAUDE_MD_START in claude_md_text
            and f"```mermaid\n{flowchart_body}```" in claude_md_text
            and expected_block_start in claude_md_text
        )

    if args.check:
        ok = mmd_fresh and claude_md_fresh
        stream = sys.stdout if ok else sys.stderr
        print(
            "render_mermaid: up to date." if ok else
            "render_mermaid: STALE — run "
            "`E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/render_mermaid.py` and commit.",
            file=stream,
        )
        return 0 if ok else 1

    if not mmd_fresh:
        MMD_OUT.write_text(rendered, encoding="utf-8")
        print(f"render_mermaid: regenerated {MMD_OUT.name}.")
    else:
        print(f"render_mermaid: {MMD_OUT.name} already up to date.")

    if not args.no_update_claude_md:
        if update_claude_md(flowchart_body):
            print(f"render_mermaid: refreshed the fleet-map block in {GLOBAL_CLAUDE_MD.name}.")
        else:
            print(f"render_mermaid: {GLOBAL_CLAUDE_MD.name} fleet-map block already up to date.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
