"""Render ``architecture/fleet.data.js`` as a Mermaid flowchart — text-native.

The PNG (`render.py`) is the human/chat artifact; this is the **agent** artifact —
a compact, always-current picture of the fleet an LLM can read as text without a
browser or an image decoder. Same single source of truth (`fleet.data.js`), a
second consumer, no new crawl logic.

Deterministic by construction, same discipline as ``build_data.py``:
* layer order is fixed (``governance``, ``enabling``, ``web``, ``pipe``);
* repos within a layer keep the array order already curated in ``fleet.data.js``;
* node ids are a plain slug of the repo's identity (``repo`` field if set, else
  ``nm`` — the same key `whatchanged.py`/`run_acceptance.py` already use), never
  derived from anything that varies run-to-run.

``architecture/system-map.mmd`` is the fleet-map doc agents open on demand —
``global-CLAUDE.md`` only points at it (moved out of always-on context under the
200-line cap, fleet-config#897). Kept deliberately lean: nodes carry **icon + name
only**, never the ``ds`` description prose (the priciest field, and already
redundant with what an agent reads once it's actually inside a given repo).
``access``/``edge``/``compute``/``external``/``principles`` are skipped entirely — narrative already covered in ``ARCHITECTURE.md``, not
repo-relationship data. Edges come only from each card's explicit ``tag`` field
(``["uses", "hub"]`` etc.) — never inferred/guessed. A tag's target text doesn't
always name another mapped repo (``"hub + whisper"``, ``"Stripe"``, …), so it gets
its own small lightweight node rather than a fuzzy match onto an existing one —
literal reflection of the curated data, not invented structure.

Usage (invoke the resolved Python path directly — see ``build_data.py``)::

    E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/render_mermaid.py          # regenerate system-map.mmd
    E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/render_mermaid.py --check  # exit 1 if system-map.mmd is stale
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DATA_JS = REPO_ROOT / "architecture" / "fleet.data.js"
MMD_OUT = REPO_ROOT / "architecture" / "system-map.mmd"

# The sections of fleet.data.js whose cards are real fleet repos, in the fixed
# render order (matches the drift guard in tests/run_acceptance.py).
SECTIONS = ["governance", "enabling", "web", "pipe"]
SECTION_TITLES = {
    "governance": "Governance",
    "enabling": "Enabling",
    "web": "Web",
    "pipe": "Pipelines",
}

HEADER = """\
%% architecture/system-map.mmd — Mermaid rendering of architecture/fleet.data.js.
%% GENERATED by .claude/skills/system-map/render_mermaid.py — DO NOT hand-edit.
%% Regenerate: E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/render_mermaid.py
%% Fleet repos by layer, icons + names only; edges come from each repo's .fleet.toml `tag` field.
"""

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slug(text: str) -> str:
    """A stable Mermaid-safe node id: lowercase, non-alnum runs collapsed to ``_``."""
    return _SLUG_RE.sub("_", text.lower()).strip("_")


def _escape(text: str) -> str:
    """Escape the one character that would break a quoted Mermaid node label."""
    return text.replace('"', "&quot;")


def load_data(js_text: str) -> dict:
    """Slice the strict-JSON object out of ``window.FLEET = { … };`` (same trick
    every other consumer of this file uses — see ``run_acceptance.py``)."""
    return json.loads(js_text[js_text.index("{"): js_text.rindex("}") + 1])


def _node_id(card: dict) -> str:
    return slug(card.get("repo", card["nm"]))


def render_flowchart(data: dict) -> str:
    """Build the flowchart body (no header comment) — pure function of ``data``."""
    lines = ["flowchart LR"]

    for section in SECTIONS:
        lines.append(f'  subgraph {section}["{SECTION_TITLES[section]}"]')
        for card in data.get(section, []):
            label = _escape(f'{card["ic"]} {card["nm"]}')
            lines.append(f'    {_node_id(card)}["{label}"]')
        lines.append("  end")

    # Edges from each card's `tag` field, in the same fixed iteration order.
    # A tag's target text gets its own lightweight node the first time it's
    # seen (dict preserves insertion order) rather than being fuzzy-matched
    # onto an existing repo node.
    target_ids: dict[str, str] = {}
    edges: list[tuple[str, str, str]] = []
    for section in SECTIONS:
        for card in data.get(section, []):
            tag = card.get("tag")
            if not tag:
                continue
            relation, target_text = tag[0], tag[1]
            target_id = target_ids.setdefault(target_text, "t_" + slug(target_text))
            edges.append((_node_id(card), relation, target_id))

    if target_ids:
        lines.append('  subgraph targets["Referenced"]')
        for text, tid in target_ids.items():
            lines.append(f'    {tid}["{_escape(text)}"]')
        lines.append("  end")

    for node_id, relation, target_id in edges:
        lines.append(f"  {node_id} -->|{relation}| {target_id}")

    return "\n".join(lines) + "\n"


def render(data: dict) -> str:
    """The full committed ``system-map.mmd`` text: header comment + flowchart."""
    return HEADER + render_flowchart(data)


def regenerate(data_path: Path = DATA_JS) -> str:
    return render(load_data(data_path.read_text(encoding="utf-8")))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render fleet.data.js as a Mermaid flowchart.")
    ap.add_argument("--check", action="store_true", help="exit 1 if system-map.mmd is stale")
    args = ap.parse_args(argv)

    rendered = regenerate()
    current = MMD_OUT.read_text(encoding="utf-8") if MMD_OUT.exists() else None
    mmd_fresh = rendered == current

    if args.check:
        ok = mmd_fresh
        stream = sys.stdout if ok else sys.stderr
        print(
            "render_mermaid: up to date." if ok else
            "render_mermaid: STALE — run "
            "`E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/system-map/render_mermaid.py` and commit.",
            file=stream,
        )
        return 0 if ok else 1

    if not mmd_fresh:
        MMD_OUT.write_text(rendered, encoding="utf-8")
        print(f"render_mermaid: regenerated {MMD_OUT.name}.")
    else:
        print(f"render_mermaid: {MMD_OUT.name} already up to date.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
