"""Deterministic post-purge checker for the `/context-purge` skill.

The purge rewrites always-on markdown (CLAUDE.md files, SKILL.md files) to cut
prose while preserving every directive. Two preservation rules are mechanically
checkable, so they live here rather than in LLM judgment (same discipline as
`context-audit/audit.py`: the helper measures, the orchestrator judges):

  1. Marked machine-managed blocks (`<!-- name:part:start -->` …
     `<!-- name:part:end -->`, e.g. the /system-map mermaid block in
     global-CLAUDE.md) must survive byte-identical — they are regenerated by
     other skills and drift fails the acceptance matrix.
  2. Quoted trigger phrases in a SKILL.md frontmatter `description:` must
     survive verbatim — they are the routing surface and are exempt from the
     prose cap precisely because they must never be reworded.

The `description:` parser and the double-quoted-trigger regex now live in
`skills/_lib/skill_description.py`, shared with `context-audit/audit.py` — the
two carried private copies and the audit's `["']` character class silently
under-counted every description containing an apostrophe (fleet-config#626).

It also prints the before/after token delta (~4 chars/token, the same estimate
audit.py trends on) so the purge report quotes exact numbers.

stdlib only. CLI:
    E:/automation/fleet-config/.venv/Scripts/python.exe .claude/skills/context-purge/check.py <before-file> <after-file>
Exit 0 = all preservation checks pass; exit 2 = at least one failed (reasons on
stdout). The semantic directive-inventory check stays with the orchestrator.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "skills" / "_lib"))
from skill_description import frontmatter_description, quoted_phrases  # noqa: E402,F401
from utf8_stdio import ensure_utf8_stdio  # noqa: E402

_MARKED_BLOCK = re.compile(
    r"<!--\s*([\w-]+:[\w-]+):start\s*-->.*?<!--\s*\1:end\s*-->", re.S
)


def est_tokens(text: str) -> int:
    """Rough token estimate (~4 chars/token) — matches audit.py's trend metric."""
    return round(len(text) / 4)


def marked_blocks(text: str) -> list[str]:
    """Every `<!-- x:y:start -->…<!-- x:y:end -->` block, whole and in order."""
    return [m.group(0) for m in _MARKED_BLOCK.finditer(text)]


def check(before: str, after: str) -> list[str]:
    """Return a list of human-readable failures (empty = pass)."""
    failures: list[str] = []

    for block in marked_blocks(before):
        if block not in after:
            label = block.splitlines()[0].strip()
            failures.append(f"marked block not byte-identical in after: {label}")

    desc_before = frontmatter_description(before)
    desc_after = frontmatter_description(after)
    if desc_before:
        if not desc_after:
            failures.append("frontmatter description: dropped entirely")
        else:
            for phrase in quoted_phrases(desc_before):
                if phrase not in desc_after:
                    failures.append(
                        f"quoted trigger phrase lost from description: {phrase}"
                    )
    return failures


def main() -> int:
    ensure_utf8_stdio()  # UTF-8 under capture (fleet gotcha) — stdout + stderr
    ap = argparse.ArgumentParser(description="Post-purge preservation checks + token delta.")
    ap.add_argument("before", type=Path)
    ap.add_argument("after", type=Path)
    args = ap.parse_args()

    before = args.before.read_text(encoding="utf-8")
    after = args.after.read_text(encoding="utf-8")

    b, a = est_tokens(before), est_tokens(after)
    pct = 0.0 if b == 0 else (b - a) * 100.0 / b
    print(f"TOKENS: before={b} after={a} saved={b - a} ({pct:.0f}%)")

    failures = check(before, after)
    for f in failures:
        print(f"FAIL  {f}")
    if not failures:
        print("PASS  marked blocks + quoted triggers preserved")
    return 0 if not failures else 2


if __name__ == "__main__":
    raise SystemExit(main())
